apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.spark.stackable.de
spec:
  group: spark.stackable.de
  names:
    kind: SparkCluster
    singular: sparkcluster
    plural: sparkclusters
    listKind: SparkClusterList
    shortNames:
      - sc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                master:
                  type: string
