apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.spark.stackable.tech
spec:
  group: spark.stackable.tech
  names:
    kind: SparkCluster
    singular: sparkcluster
    plural: sparkclusters
    listKind: SparkClusterList
    shortNames:
      - sc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                master:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          node_name:
                            type: string
                          instances:
                            type: integer
                          port:
                            type: integer
                          web_ui_port:
                            type: integer
                worker:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          node_name:
                            type: string
                          instances:
                            type: integer
                          cores:
                            type: integer
                          memory:
                            type: string
                history_server:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          node_name:
                            type: string
                          instances:
                            type: integer
                version:
                  type: string
                secret:
                  type: string
                log_dir:
                  type: string
            status:
              type: object
              properties:
                version:
                  type: string
