apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stops.command.spark.stackable.tech
spec:
  group: command.spark.stackable.tech
  names:
    kind: Stop
    singular: stop
    plural: stops
    listKind: StopList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
            status:
              nullable: true
              type: object
              properties:
                startedAt:
                  type: string
                finishedAt:
                  type: string
                message:
                  type: string
      subresources:
        status: { }