apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - node_name: "mdesktop"
        instances: 1
        cores: "1"
        memory: "1g"
  worker:
    selectors:
      - node_name: "mdesktop"
        instances: 2
        cores: "2"
        memory: "1g"
  image: "spark:3.0.1"
  secret: "very_secret"

