apiVersion: spark.stackable.de/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  nodes:
    selectors:
      - node_type: "master"
        node_name: "mdesktop"
        instances: 1
        cores: "1"
        memory: "1g"
      - node_type: "worker"
        node_name: "mdesktop"
        instances: 1
        cores: "1"
        memory: "2g"
  image: "spark:3.0.1"
  secret: "very_secret"

