apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - node_name: "mdesktop"
        instances: 1
  worker:
    selectors:
      - node_name: "mdesktop"
        instances: 1
        cores: 1
        memory: "1g"
#      - node_name: "mdesktop"
#        instances: 1
#        cores: 2
#        memory: "2g"
  history_server:
    selectors:
      - node_name: "mdesktop"
        instances: 1
  image:
    name: "spark"
    version: "3.0.1"
#  secret: "very_secret"


